# Default values for votingsample-resultsapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: askstacr.azurecr.io/votingsample/results-app
  tag: #{version}
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  name: votingsample-resultsapp
  type: ClusterIP
  port: 443
  internalPort: 443

ingress:
  enabled: true
  traefik_v2: false
  annotations:
    #kubernetes.io/ingress.class: traefik
    #traefik.ingress.kubernetes.io/rewrite-target: "/"
    #traefik.ingress.kubernetes.io/rule-type: PathPrefixSplit
  path: /result
  tls: []

deployment:
  annotations:
    orgs.k8s.snyk.io/v1: 78ddc5c1-6c2b-4cec-afd2-897c28ef9ad4

configuration:
  ConnectionString: Server=votingsampleapps-msyql-mysql;Port=3306;Database=votes;User=root;Password=testing;SslMode=None

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
