apiVersion: v1
kind: Secret
metadata:
  name: {{ include "votingsample-votingapp.fullname" . }}-settings
type: Opaque
data:
  certificate_path: {{ .Values.configuration.certificate_path | b64enc }}
  certificate_password: {{ .Values.configuration.certificate_password | b64enc }}
  aspnetcore_urls: {{ .Values.configuration.aspnetcore_urls | b64enc }}
  MessageQueue_Url: {{ .Values.configuration.MessageQueue_Url | b64enc }}
