apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-settings
type: Opaque
data:
  MessageQueue_Url: {{ .Values.configuration.MessageQueue_Url | b64enc }}
  ConnectionStrings_VoteData: {{ .Values.configuration.ConnectionString | b64enc }}
