apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: votingsample-mysql
  namespace: flux-vote
spec:
  releaseName: votingsample-mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: mysql
    version: 1.6.6
  values:
    mysqlRootPassword: testing
