apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: votingsample-mysql
  namespace: flux-vote
spec:
  releaseName: votingsample-mysql
  targetNamespace: vote
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mysql
    version: 7.1.0
  values:
    root:
      password: testing
    replication:
      enabled: false
