apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: votingsample-nats
  namespace: flux-vote
spec:
  releaseName: votingsample-nats
  targetNamespace: vote
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nats
    version: 5.0.0
  values:
    auth:
      enabled: false
