apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: votingsample-nats
  namespace: flux-vote
spec:
  releaseName: votingsample-nats
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nats
    version: 4.3.7
  values:
    auth:
      enabled: false
