apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: votingsample-votingapp
  namespace: flux-vote
spec:
  releaseName: votingsample-votingapp
  chart:
    git: https://github.com/asos-philc/arc-helm-demo
    ref: master
    path: charts/votingsample-votingapp
  values:
    image:
      repository: asnpeuwphiacr.azurecr.io/votingsample/voting-app
      tag: 0.0.0-local
    ingress:
      traefik_v2: true
    configuration:
      MessageQueue_Url: "nats://votingsample-nats-client:4222"
