{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: cert-manager.io/v1alpha2
{{- else }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- end }}
kind: Certificate
metadata:
  name: {{ include "votingsample-resultsapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "votingsample-resultsapp.name" . }}
    helm.sh/chart: {{ include "votingsample-resultsapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ include "votingsample-resultsapp.fullname" . }}-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: {{ include "votingsample-resultsapp.fullname" . }}
  organization:
  - Voting Sample Application
