apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "votingsample-resultsapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "votingsample-resultsapp.name" . }}
    helm.sh/chart: {{ include "votingsample-resultsapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "votingsample-resultsapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "votingsample-resultsapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ConnectionStrings__ResultData
            valueFrom:
              secretKeyRef:
                name: {{ include "votingsample-resultsapp.fullname" . }}-settings
                key: ConnectionStrings_ResultData
        - name: {{ .Chart.Name }}-nginx
          image: nginx:1.17.7-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls-volume
              mountPath: /etc/ssl/private
            - name: vhost-volume
              mountPath: /etc/nginx/conf.d
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /result
              port: http
          readinessProbe:
            httpGet:
              path: /result
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: tls-volume
        secret:
          secretName: {{ include "votingsample-resultsapp.fullname" . }}-tls
      - name: vhost-volume
        configMap:
          name: {{ include "votingsample-resultsapp.fullname" . }}-vhost
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
