apiVersion: v1
kind: Secret
metadata:
  name: {{ include "votingsample-resultsapp.fullname" . }}-settings
type: Opaque
data:
  ConnectionStrings_ResultData: {{ .Values.configuration.ConnectionString | b64enc }}
